version: '3.9'

services:
  authenticator_service:
    build: .
    container_name: authenticator_service
    command: gunicorn authenticator_service.wsgi:application 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=authenticator_service.settings
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
    networks:
      - default

  db:
    image: postgres:17.2-alpine
    container_name: prohub_auth_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:4.0.5-management
    container_name: prohub_rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_HOST}
      RABBITMQ_URI: ${RABBITMQ_URL}
  
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - ./media:/app//media
    environment:
      - MAIN_DOMAIN_NAME=${MAIN_DOMAIN_NAME}
    networks:
      - default

networks:
  default:
    driver: bridge